package gae_imptest

import (
	"net/http"

	_ "appengine"
	_ "appengine/blobstore"
	_ "appengine/capability"
	_ "appengine/channel"
	_ "appengine/datastore"
	_ "appengine/delay"
	_ "appengine/file"
	_ "appengine/image"
	_ "appengine/log"
	_ "appengine/mail"
	_ "appengine/memcache"
	_ "appengine/remote_api"
	_ "appengine/runtime"
	_ "appengine/socket"
	_ "appengine/taskqueue"
	_ "appengine/urlfetch"
	_ "appengine/user"
	_ "appengine/xmpp"
	_ "archive/tar"
	_ "archive/zip"
	_ "bufio"
	_ "bytes"
	_ "code.google.com/p/goprotobuf/proto"
	_ "compress/bzip2"
	_ "compress/flate"
	_ "compress/gzip"
	_ "compress/lzw"
	_ "compress/zlib"
	_ "container/heap"
	_ "container/list"
	_ "container/ring"
	_ "crypto"
	_ "crypto/aes"
	_ "crypto/cipher"
	_ "crypto/des"
	_ "crypto/dsa"
	_ "crypto/ecdsa"
	_ "crypto/elliptic"
	_ "crypto/hmac"
	_ "crypto/md5"
	_ "crypto/rand"
	_ "crypto/rc4"
	_ "crypto/rsa"
	_ "crypto/sha1"
	_ "crypto/sha256"
	_ "crypto/sha512"
	_ "crypto/subtle"
	_ "crypto/tls"
	_ "crypto/x509"
	_ "crypto/x509/pkix"
	_ "database/sql"
	_ "database/sql/driver"
	_ "debug/dwarf"
	_ "debug/elf"
	_ "debug/gosym"
	_ "debug/macho"
	_ "debug/pe"
	_ "encoding/ascii85"
	_ "encoding/asn1"
	_ "encoding/base32"
	_ "encoding/base64"
	_ "encoding/binary"
	_ "encoding/csv"
	_ "encoding/gob"
	_ "encoding/hex"
	_ "encoding/json"
	_ "encoding/pem"
	_ "encoding/xml"
	_ "errors"
	_ "expvar"
	_ "flag"
	_ "fmt"
	_ "go/ast"
	_ "go/build"
	_ "go/doc"
	_ "go/parser"
	_ "go/printer"
	_ "go/scanner"
	_ "go/token"
	_ "hash"
	_ "hash/adler32"
	_ "hash/crc32"
	_ "hash/crc64"
	_ "hash/fnv"
	_ "html"
	_ "html/template"
	_ "image"
	_ "image/color"
	_ "image/draw"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	_ "index/suffixarray"
	_ "io"
	_ "io/ioutil"
	_ "log"
	_ "log/syslog"
	_ "math"
	_ "math/big"
	_ "math/cmplx"
	_ "math/rand"
	_ "mime"
	_ "mime/multipart"
	_ "net"
	_ "net/http/cgi"
	_ "net/http/httptest"
	_ "net/http/httputil"
	_ "net/http/pprof"
	_ "net/mail"
	_ "net/rpc"
	_ "net/rpc/jsonrpc"
	_ "net/smtp"
	_ "net/textproto"
	_ "net/url"
	_ "os"
	_ "path"
	_ "path/filepath"
	_ "reflect"
	_ "regexp"
	_ "regexp/syntax"
	_ "runtime"
	_ "sort"
	_ "strconv"
	_ "strings"
	_ "sync"
	_ "sync/atomic"
	_ "testing"
	_ "testing/iotest"
	_ "testing/quick"
	_ "text/scanner"
	_ "text/tabwriter"
	_ "text/template"
	_ "text/template/parse"
	_ "time"
	_ "unicode"
	_ "unicode/utf16"
	_ "unicode/utf8"

	_ "github.com/goforks/blackfriday"
	_ "github.com/goforks/toml"
	_ "github.com/gorilla/context"
	_ "github.com/gorilla/mux"

	//	KEEP lines in between the following metaleap/go-util imps
	//	for dependency-sorting instead of alphabetical

	_ "github.com/metaleap/go-util"

	_ "github.com/metaleap/go-util/empty_for_testing"

	_ "github.com/metaleap/go-util/num"

	_ "github.com/metaleap/go-util/gfx" // --> imps go-util/num

	_ "github.com/metaleap/go-util/hash"

	_ "github.com/metaleap/go-util/slice"

	_ "github.com/metaleap/go-util/slice/sort"

	_ "github.com/metaleap/go-util/str" // --> imps go-util & go-util/slice

	_ "github.com/metaleap/go-util/io" // --> imps go-util/str

	_ "github.com/metaleap/go-util/net" // --> imps go-util/io
)

func init() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Hello " + r.Header.Get("User-Agent") + " User!"))
	})
}
